---
version: 2
updates:
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    # open-pull-requests-limit: 5
    groups:
      maven-plugin-dependencies:
        patterns:
          - "org.apache.maven.plugins*"
      quarkus-dependencies:
        patterns:
          - "io.quarkus:*"
          - "io.quarkus.platform:*"
          - "io.quarkus.*"
      dummy-data-dependencies:
        patterns:
          - "org.instancio:*"
          - "net.datafaker:*"
        update-types:
          - "minor"          
    ignore:
      - dependency-name: "io.quarkus*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "org.instancio:*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "net.datafaker:*"
        update-types: ["version-update:semver-patch"]
